### ISSUE TITLE
Multiple conky scripts?

### ISSUE THREAD

**Issue by bezze** [varingst/awesome-conky#1]
Is there a way to have several conky scripts running? i.e. a process running conkyrc0, another conkyrc1, etc ...

**Comment by varingst** [comment]
Yes and no.

Conky-awesome doesn't really care about your conkyrc. It only cares that one conky process is running with the provided dbus module. You may run as many other conky processes with other configurations as you please.

Conky-awesome will launch a conky process with the configuration in ~/.conkyrc when awesome starts. There is currently no way to change which conkyrc conky will be launched with, because there's no good reason to, just use other configuration files for the extra processes.

Conky-awesome provides keybindings for raising conky's own window, but if you're running multiple processes I'm assuming you're using these to draw on the desktop root window, which is the 'default and intended' mode of conky.

If what you want is several conky processes, each with their own separate window, conky-awesome will not provide separate keybindings for each of them, it only expects one window. Conky-awesome finds the window by matching WM_CLASS == "Conky", and if there's several matches, it will only interact with the first of them. So if you want to have several separate windows I suggest you use the conky configuration variable `own_window_class` to set the class to something else for your other windows, and then create rules in `awesome/rc.lua` to catch and handle those clients.

An actual usecase or more specific description of what you intend to do would let me answer better, but if you keep the loading of the provided dbus module in ~/.conkyrc, you can do whatever you want with other conky processes and configuration files.

I'll close this here as a generic answer to a generic question, if you have specific issues with specific configurations, please open another issue.
